# GoReleaser config

before:
  hooks:
    - go mod tidy

builds:
- id: jornada_darwin
  binary: jornada
  main: './cmd/jornada/main.go'
  goos:
    - darwin
  goarch:
    - amd64
  env:
    - CGO_ENABLED=1
    - CC=o64-clang
    - CXX=o64-clang++
  flags:
    - -tags
    - sqlite

- id: jornada_linux
  binary: jornada
  main: './cmd/jornada/main.go'
  env:
    - CGO_ENABLED=1
  flags:
    - -tags
    - sqlite
  goos:
    - linux
  goarch:
    - amd64

- id: jornada_windows_x64
  binary: jornada
  main: './cmd/jornada/main.go'
  ldflags:
    - "-extldflags '-static'"
  env:
    - CGO_ENABLED=1
    - CC=x86_64-w64-mingw32-gcc
    - CXX=x86_64-w64-mingw32-g++
  flags:
    - -tags
    - sqlite
  goos:
    - windows
  goarch:
    - amd64

archives:
  - format_overrides:
    - goos: 'windows'
      format: 'zip'

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: 'asc'
  filters:
    exclude: ['^docs:', '^test:', 'Merge pull request', 'Merge branch']

dockers:
  - image_templates:
    - 'brunoluiz/jornada:{{ .Tag }}'
    - 'brunoluiz/jornada:v{{ .Major }}.{{ .Minor }}'
    - 'brunoluiz/jornada:latest'
    dockerfile: 'Dockerfile.prod'
    binaries:
    - jornada

brews:
  - tap:
      owner: 'brunoluiz'
      name: 'homebrew-tap'
    folder: 'Formula'
