name: goreleaser

on:
  create:
    tags:
      - v*.*.*

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    container:
      image: bepsays/ci-goreleaser:1.16.0
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      -
        name: Install Docker
        run: |
          apt-get update
          apt-get install apt-transport-https ca-certificates curl gnupg-agent software-properties-common -y
          curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -
          add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/debian $(lsb_release -cs) stable"
          apt-get update
          apt-get install docker-ce docker-ce-cli containerd.io -y
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
